// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7BX4vmWpGDDIUrM4XDIp_iAi7stoQq9o',
    appId: '1:934856756615:web:204e3dd0419818d335d722',
    messagingSenderId: '934856756615',
    projectId: 'chantierplus-b9b6a',
    authDomain: 'chantierplus-b9b6a.firebaseapp.com',
    storageBucket: 'chantierplus-b9b6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArx9o5b_bbu6ZYl51VCG_4TnX64vgvKlg',
    appId: '1:934856756615:android:bd0f3c53e4481dfd35d722',
    messagingSenderId: '934856756615',
    projectId: 'chantierplus-b9b6a',
    storageBucket: 'chantierplus-b9b6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hHGRs1B5GtWzfuhP6CHxtcHor0AMLVI',
    appId: '1:934856756615:ios:a4d1d7d9da8759c235d722',
    messagingSenderId: '934856756615',
    projectId: 'chantierplus-b9b6a',
    storageBucket: 'chantierplus-b9b6a.firebasestorage.app',
    iosBundleId: 'com.example.chantierPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4hHGRs1B5GtWzfuhP6CHxtcHor0AMLVI',
    appId: '1:934856756615:ios:a4d1d7d9da8759c235d722',
    messagingSenderId: '934856756615',
    projectId: 'chantierplus-b9b6a',
    storageBucket: 'chantierplus-b9b6a.firebasestorage.app',
    iosBundleId: 'com.example.chantierPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7BX4vmWpGDDIUrM4XDIp_iAi7stoQq9o',
    appId: '1:934856756615:web:44027fb90b2d610b35d722',
    messagingSenderId: '934856756615',
    projectId: 'chantierplus-b9b6a',
    authDomain: 'chantierplus-b9b6a.firebaseapp.com',
    storageBucket: 'chantierplus-b9b6a.firebasestorage.app',
  );
}
